language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
#  - hhvm
  
before_script:
  - composer selfupdate
  - composer install --prefer-source
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

script: 
  - phpunit --coverage-text --coverage-clover /tmp/oliviermadre/dicit/coverage.xml
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/oliviermadre/dicit/coverage.xml
  - ./vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame ./src
